language: r
sudo: required
cache: packages
warnings_are_errors: false
r: devel
r_packages:
- devtools
- ade4
- Cairo
- dplyr
- energy
- FD
- gcookbook
- GGally
- ggplot2
- ggrepel
- Hmisc
- knitr
- lme4
- maptree
- MASS
- Matrix
- memoise
- minet
- moments
- qvalue
- reshape2
- rmarkdown
- robustbase
- rpart
- scales
- survival
- tgp
- tidyr
- vegan
- ggpubr
- tidyverse
- pheatmap
- data.table
#bioc_packages:
r_github_packages:
- cran/RUnit
- joey711/phyloseq
- microbiome/microbiome
#- microsud/microbiomeutilities
- jimhester/covr

