language: r
sudo: required
cache: packages
warnings_are_errors: false
r_packages:
- ade4
- bayesm
- Cairo
- dplyr
- energy
- FD
- gcookbook
- GGally
- ggplot2
- ggrepel
- hrbrthemes
- Hmisc
- intergraph
- knitr
- lme4
- maptree
- MASS
- Matrix
- memoise
- minet
- mixOmics
- moments
- network
- qvalue
- reshape2
- rmarkdown
- robustbase
- rpart
- scales
- survival
- tgp
- Rtsne
- tidyr
- vegan
- WGCNA
- ggpubr
- tidyverse
- pheatmap
- data.table
bioc_packages:
- BiocInstaller
- DESeq2
- phyloseq
r_github_packages:
- cran/RUnit
- microbiome/microbiome
- jimhester/covr
